name: Add a label when a issue is opened
on:
  issues:
    types:
      - opened
      - edited
jobs:
  apply-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add Label
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title;
            const labelsToAdd = [];
            if(title.toLowerCase().includes('bug')){
                labelsToAdd.push('bug');
            }
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labelsToAdd
            });
            
