name: build-deploy
on:
  push:
    branches:
      - main
jobs:
  build-jar-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: 21
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-spring-boot-app
          path: '${{github.workspace}}/target/*.jar'
  deploy-jar-file:
    runs-on: ubuntu-latest
    needs: build-jar-file
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: java-spring-boot-app

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'chetan-webservice'
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: '*.jar'
