name: Test Building the project
on:
  push:
    branches:
      - main

jobs:
  build-project:
    name: Build the project using maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'maven'

      - name: Compile the project
        run: mvn clean install
